### ISSUE TITLE
Document advised git workflow?

### ISSUE THREAD

**Issue by bravo-kernel** [gkubisa/elm-app-boilerplate#11]
Nice job on the boilerplate. Would you welcome a small readme section describing advised git workflow when using your boilerplate as a seed project? If so, I will create a draft.

**Comment by gkubisa** [comment]
Thanks for the idea, @bravo-kernel . Honestly, I'm a bit reluctant to include such section, because different workflows are suitable for different projects and organizations. Consequently, I don't think that documenting a specific workflow would provide any tangible benefits to the users of this project.

It would be in order to document the workflow for contributions to 'elm-app-boilerplate` itself, however, at the current scale I don't see the need.

**Comment by bravo-kernel** [comment]
:white_check_mark:
