### ISSUE TITLE
my mktemp has no --suffix flag

### ISSUE THREAD

**Issue by ChetHarrison** [gkubisa/elm-app-boilerplate#14]
I am running bash GNU bash, version 4.3.39(1)-release (x86_64-apple-darwin14.4.0). I must admit my bash is weak but my version of mktemp does not have a `suffix` flag. do you have any suggestions on how I should modify the `npm run test:elm` script? Thanks!

**Comment by gkubisa** [comment]
I must admin I didn't put much effort into making this repo cross platform :-( . `FILE="$(mktemp /tmp/elm-XXXXXXXXXXXX.js)"` should do the trick.

Anyway, for unit tests I would recommend using [elm-test](https://github.com/rtfeldman/node-test-runner), which has been improved recently, so that I could integrate it into elm-app-boilerplate on the [navigation branch](https://github.com/gkubisa/elm-app-boilerplate/tree/navigation). The branch is almost ready for a merge to master and I just need to find a bit of time to polish it a bit.

So, I'd recommend you either switch to the `navigation` branch of `elm-app-boilerplate` or just integrate `elm-test` directly into your project.

**Comment by ChetHarrison** [comment]
Ok. Thanks!

On Oct 24, 2016, at 4:03 PM, Greg Kubisa <notifications@github.com> wrote:

I must admin I didn't put much effort into making this repo cross platform :-( . FILE="$(mktemp /tmp/elm-XXXXXXXXXXXX.js)" should do the trick.

Anyway, for unit tests I would recommend using elm-test <https://github.com/rtfeldman/node-test-runner>, which has been improved recently, so that I could integrate it into elm-app-boilerplate on the navigation branch <https://github.com/gkubisa/elm-app-boilerplate/tree/navigation>. The branch is almost ready for a merge to master and I just need to find a bit of time to polish it a bit.

So, I'd recommend you either switch to the navigation branch of elm-app-boilerplate or just integrate elm-test directly into your project.

**Comment by gkubisa** [comment]
`mktemp` is not used by elm-app-boilerplate as of https://github.com/gkubisa/elm-app-boilerplate/releases/tag/v0.4.0
