### ISSUE TITLE
npm start, `You may need an appropriate loader to handle this file type.`

### ISSUE THREAD

**Issue by AbrahamAlcaina** [gkubisa/elm-app-boilerplate#17]
I just clone, npm install, elm install -y and when I try to start I received the follow error:
```
$ npm run start

> elm-app-boilerplate@0.6.0 start C:\git\elm-app-boilerplate
> webpack-dev-server --hot --inline

Project is running at http://localhost:8080/
webpack output is served from /
404s will fallback to /index.html

ERROR in ./elm/Stylesheets.elm
Module parse failed: C:\git\elm-app-boilerplate\elm\Stylesheets.elm Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| port module Stylesheets exposing (main)
|
| import App.Section.Root.Css as SectionRoot
 @ ./js/main.js 2:0-27
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./js/main.js

ERROR in ./elm/Main.elm
Module parse failed: C:\git\elm-app-boilerplate\elm\Main.elm Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| module Main exposing (main)
|
| import Navigation
 @ ./js/main.js 3:0-29
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./js/main.js
webpack: Failed to compile.
```

**Comment by gkubisa** [comment]
Thanks for reporting it @AbrahamAlcaina .

I don't have a Windows machine to test it right now but I think the problem is that Windows uses `\` as a file separator while I assumed it's `/` in `webpack.config.babel.js`.

Try replacing `/` with `\` in the regular expressions:

- `noParse: /\/Main\.elm$/,` -> `noParse: /\\Main\.elm$/,`
- `test: /\/Main\.elm$/,` -> `test: /\\Main\.elm$/,`
- `test: /\/Stylesheets\.elm$/,` -> `test: /\\Stylesheets\.elm$/,`

I'll push a fix to this repo later, once I verify that it works on all platforms.

**Comment by AbrahamAlcaina** [comment]
I solved the issue in windows, when I change it in that way:
`test: /Main\.elm$/,` without /

**Comment by gkubisa** [comment]
Cool. The reason I added `/` was to ensure that only files called exactly `Main.elm` were matched, not any files which end in `Main.elm`. It's not a big deal and I'm happy that you found a solution. :-)
